### PR TITLE
Create best_batchers

### PR DESCRIPTION
**Pull request by janweinreich**
project suggestion for the coming BO hackathon, team and project "best batchers".

@sgbaird 
@rlaplaza
@dkhan42 <- may join (not certain yet)
@briling <- may join (not certain yet)

### CODE REVIEW

**Comment by sgbaird** [comment]
Looks great! I made a couple minor changes, feel free to change as needed. I'm excited to see what you find about dynamic batch sizes.

**Comment by janweinreich** [comment]
thanks! do I have to update the team members here for the final team composition before the start of the hackathon?

**Comment by sgbaird** [comment]
If by here, you mean tagging them on the GitHub issue, that's optional. For the actual project file displayed on the website, this will ideally be kept up to date through separate pull requests.

**Comment by sgbaird** [comment]
For convenience, here's the direct link: https://github.com/AC-BO-Hackathon/ac-bo-hackathon.github.io/edit/main/_projects/project-15-best_batchers.md, which you can find at the bottom of the project page - "Improve this page".

**Pull request merged**
