### PR TITLE
Create project-BO-Campaigns.md

### PR DESCRIPTION
**Pull request by Schubydo**
@jakobzeitler

### CODE REVIEW

**Comment by sgbaird** [comment]
Hi @Schubydo, thanks for the proposal! Do you mind including a bit more detail in the description?

**Comment by jakobzeitler** [comment]
Hi @sgbaird !

I have sent the other project team and email, to see if they'd like to join forces.

The project description could be updated to:

"Bayesian Optimisation in Synthetic Biology is an emerging topic. Traditionally, classical DoE by design gives some insight into the interaction of input variables such as vitamins or trace materials.

In a BO campaign, we can efficiently navigate that high dimensional input space, but we are not getting a direct insight into the interactions between variables.

Therefore, it is important to provide some additional insight apart from where possible (local) maxima are. For example, what are the driving forces of high cell yield? What are the key interactions?


In this project, we investigate how the literature so far has treated the interpretation of BO campaigns, review methods for insight generation and brainstorm ways of how to extend those to synthetic biology in general.

**Comment by sgbaird** [comment]
@jakobzeitler sounds good! Totally up to you (and the other team) if you want to merge, but I think there's value to both approaches. At the very least, I think it would be helpful for the two teams to be aware of each other's projects and chat, whether or not the teams merge.

Lmk the status on that so I can know whether to merge or not 👍

**Comment by jakobzeitler** [comment]
I think for now let's keep them separate, and merge this project description. 

We can always combine the projects as we go! Thanks!

**Comment by sgbaird** [comment]
Great! I also updated the filename to make it more specific to interpretability. Feel free to change back.

**Comment by jakobzeitler** [comment]
Yes, I saw that, too, but failed to change it, not a GitHub genius enough I am, ha!

On 21 Mar 2024, at 16:53, Sterling G. Baird ***@***.***> wrote:


⚠ Caution: External sender



Great! I also updated the filename to make it more specific to interpretability. Feel free to change back.

**Pull request merged**
