### PR TITLE
Update project-27-bayes-warmup.md

### PR DESCRIPTION
**Pull request by eltonpan**
update youtube video link

### CODE REVIEW

**Comment by eltonpan** [comment]
Can I confirm whether this constitutes a full submission (i.e. github repo + youtube video)? thanks!

**Comment by sgbaird** [comment]
Hi @eltonpan , sorry for the delay. Yes, this is fine! Do you mind also adding a LinkedIn and X post? Otherwise should be good to merge.

**Comment by eltonpan** [comment]
Sure, I will get a member of the team to do that. Looking forward to the merge. Thanks!

**Comment by sgbaird** [comment]
Awesome, thanks!

**Pull request merged**
