### PR TITLE
Update project-35-gauche.md

### PR DESCRIPTION
**Pull request by Ryan-Rhys**
Adding link to tutorial notebooks.

### CODE REVIEW

**Comment by sgbaird** [comment]
@Ryan-Rhys nice! Do you mind also adding affiliations and GitHub usernames?

e.g.,
`Sterling Baird (Acceleration Consortium) @sgbaird`

**Comment by Ryan-Rhys** [comment]
Done!

**Comment by sgbaird** [comment]
@Ryan-Rhys thanks! Also, sorry for not catching first - do you have the two minute video and social media post attached to this project?

(Https://ac-bo-hackathon.github.io/submission). I can merge now and wait on the next PR if you need some time still

**Comment by sgbaird** [comment]
bump

**Pull request merged**
