### PR TITLE
video and LinkedIn updated typo corrected

### PR DESCRIPTION
**Pull request by bznan**

### CODE REVIEW

**Comment by bznan** [comment]
Project-40

**Comment by sgbaird** [comment]
@bznan thanks for adding the video! Also, by LinkedIn or X post, I mean a post where you share about the project. Will you add that please? Also add the GitHub usernames of each team member here as well, in the following format:

`Sterling Baird (Acceleration Consortium) @sgbaird`

Thanks for the patience through this!

**Comment by bznan** [comment]
Sure, working on it.

**Comment by bznan** [comment]
Kehan Guo (University of Notre Dame) @KehanGuo2 
Taicheng Guo (University of Notre Dame) @taichengguo
Yanqiao Zhu (UCLA) @SXKDZ

**Comment by bznan** [comment]
Hi I just updated collaborator information and the link of the video post.

**Comment by sgbaird** [comment]
Great, thank you!

**Pull request merged**
