### PR TITLE
Updated project file

### PR DESCRIPTION
**Pull request by T-NIKHIL**

### CODE REVIEW

**Comment by sgbaird** [comment]
Great! Can you also add a link to a social media post for the project? (E.g., LinkedIn)

**Comment by T-NIKHIL** [comment]
It should be there in the project file. I am also pasting it here : https://youtu.be/iog-07Ekp9g

**Comment by sgbaird** [comment]
Oh, sorry - I mean like LinkedIn or X. I need to update the submission instructions to be clearer for next time.

**Comment by T-NIKHIL** [comment]
We didn't post there actually. I can make one right now and send it it you.

**Comment by T-NIKHIL** [comment]
I contacted my team members about it. Ill be able to give you an update tomorrow.

**Comment by T-NIKHIL** [comment]
Here's the link to the post : https://twitter.com/nik_thota/status/1775733790335226170?s=61&t=VX1lLj215XQnDDvTWRpXJg

**Comment by sgbaird** [comment]
Amazing, thanks!

**Pull request merged**
