### PR TITLE
Update project-32-AiChemMcGill.md

### PR DESCRIPTION
**Pull request by ngastellu**
Added the proper repository name to our project file, and included the YouTube ID of our video submission.

### CODE REVIEW

**Comment by sgbaird** [comment]
@ngastellu can you update with Github usernames too?
e.g.,
`Sterling Baird (Acceleration Consortium) @sgbaird`

**Comment by ngastellu** [comment]
Done!

**Comment by sgbaird** [comment]
Amazing, thank you! Sorry, one last piece. Can you include a link to a social media post as well (LinkedIn, X, etc.)?

**Comment by ngastellu** [comment]
Just added the social media link!

**Comment by sgbaird** [comment]
Amazing! Thanks!

**Pull request merged**
