### PR TITLE
Create project-SimpleGPT-BO.md

### PR DESCRIPTION
**Pull request by arifin-chemist89**

### CODE REVIEW

**Comment by sgbaird** [comment]
Hi @arifin-chemist89, interested to hear more on this! Feel free to update the project details later if needed.

**Comment by sgbaird** [comment]
I was chatting with @jduerholt who manages the BoFire project (https://github.com/jduerholt). He will be on vacation, but he noticed your project and mentioned that BoFire might be a good fit since it uses pydantic under the hood to help impose some structure.

He said you're welcome to reach out to him directly. Not sure if he wants his email here, so I'll send to you separately.

**Comment by arifin-chemist89** [comment]
@sgbaird thank you very much arranging the projects. My idea was as simple as to build MyGPT on ChatGPT platform to do BO. It is easy to build since we only need to generate the intructions and some python code to suggest candidates. However, this has minus point because it only can be accessed by the users that has access to the ChatGPT+. If we develop better applications to use the API, it could be more general way to do it. I will contact @jduerholt directly and ask him about the idea.

**Comment by sgbaird** [comment]
@arifin-chemist89, since more people have been expressing interest and looking at the project descriptions, do you mind updating the project description with a bit more detail? No worries if you want to leave as is.

**Pull request merged**
